name: churn-inference
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - scikit-learn==1.3.2
      - pandas==2.1.4
      - mlflow==2.9.2
      - azureml-mlflow==1.57.0
      - numpy>=1.24.0
      - joblib>=1.3.0
